version: '3.1'
services:
  matomo:
    image: "matomo:fpm-alpine"
    volumes:
      - ../matomo:/var/www/html
      - ./docker-compose-etc/matomo.php.ini:/usr/local/etc/php/conf.d/matomo.php.ini
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    container_name: matomo-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./.mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
  nginx:
    image: bitnami/nginx
    container_name: matomo-nginx
    restart: always
    links:
      - matomo
    volumes:
      - ./docker-compose-etc/server_block.conf:/opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:ro
      - ../matomo:/var/www/html
    ports:
      - "3000:8080"

